# Generated by Django 3.2.6 on 2021-08-25 09:31

from django.db import migrations


def data_filling(apps, schema_editor):
    Department = apps.get_model("department_app", "Department")
    Specialization = apps.get_model("department_app", "Specialization")
    Positions = apps.get_model("department_app", "Positions")
    Department.objects.create(department="Finance")
    Department.objects.create(department="Marketing")
    Department.objects.create(department="Developer")
    Specialization.objects.create(name='Python')
    Specialization.objects.create(name='C#')
    Specialization.objects.create(name='Java')
    Specialization.objects.create(name='C++')
    Positions.objects.create(name='Senior')
    Positions.objects.create(name='Middle')
    Positions.objects.create(name='Junior')
    Positions.objects.create(name='Student')


class Migration(migrations.Migration):
    dependencies = [
        ('department_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(data_filling),
    ]
