# Generated by Django 3.2.6 on 2021-08-25 09:58

from django.db import migrations

def data_filling(apps, schema_editor):
    Employee = apps.get_model("department_app", "Employee")
    Employee.objects.create(name='Ihar Nauros', date_of_birth='1990-01-01', department_id=36, experience=15,
                            wages=1500, positions_id=41, specialization_id=42)
    Employee.objects.create(name='Svirydzetski Kanstantsin', date_of_birth='1998-05-05', experience=1, wages=10,
                            department_id=36, positions_id=44, specialization_id=42)


class Migration(migrations.Migration):

    dependencies = [
        ('department_app', '0004_auto_20210825_1254'),
    ]

    operations = [
        migrations.RunPython(data_filling),
    ]
